const data = [
    {
      id: 1,
      name: 'John Doe',
      age: 25,
      email: 'john.doe@example.com',
      city: 'New York',
    },
    {
      id: 2,
      name: 'Jane Smith',
      age: 30,
      email: 'jane.smith@example.com',
      city: 'Los Angeles',
    },
    {
      id: 3,
      name: 'Jane Snow',
      age: 49,
      email: 'jane.snow@example.com',
      city: 'Los Angeles',
    },
    {
      id: 4,
      name: 'Carrey Snow',
      age: 30,
      email: 'carrey.snow@example.com',
      city: 'Denver',
    },
    {
      id: 5,
      name: 'Wick Snow',
      age: 30,
      email: 'wick.snow@example.com',
      city: 'New York',
    },
    {
      id: 6,
      name: 'Emma Davis',
      age: 28,
      email: 'emma.davis@example.com',
      city: 'Seattle',
    },
    {
      id: 7,
      name: 'Daniel Brown',
      age: 32,
      email: 'daniel.brown@example.com',
      city: 'Denver',
    },
    {
      id: 8,
      name: 'John Wick',
      age: 32,
      email: 'John.wick@example.com',
      city: 'New York',
    },
    {
      id: 9,
      name: 'Carly Smith',
      age: 12,
      email: 'John.wick@example.com',
      city: 'San Diego'
    },
    {
      id: 10,
      name: 'Jeffrey Bezoz',
      age: 70,
      email: 'Jeff.bezoz@example.com',
      city: 'Dallas',
    },
    {
      id: 11,
      name: 'John Kennedy',
      age: 22,
      email: 'Jfk@example.com',
      city: 'Chicago',
    },
    {
      id: 15,
      name: 'Michael Johnson',
      age: 35,
      email: 'michael.johnson@example.com',
      city: 'Chicago',
    },
    {
      id: 16,
      name: 'Olivia Wilson',
      age: 27,
      email: 'olivia.wilson@example.com',
      city: 'Boston',
    },
    // New people
    {
      id: 17,
      name: 'Emily Johnson',
      age: 33,
      email: 'emily.johnson@example.com',
      city: 'Chicago',
    },
    {
      id: 18,
      name: 'Michael Smith',
      age: 27,
      email: 'michael.smith@example.com',
      city: 'Los Angeles',
    },
    {
      id: 19,
      name: 'Sophia Brown',
      age: 29,
      email: 'sophia.brown@example.com',
      city: 'New York',
    },
    {
      id: 20,
      name: 'Joshua Davis',
      age: 31,
      email: 'joshua.davis@example.com',
      city: 'Seattle',
    },
    {
      id: 21,
      name: 'Olivia Johnson',
      age: 26,
      email: 'olivia.johnson@example.com',
      city: 'Miami',
    },
    {
      id: 22,
      name: 'William Smith',
      age: 35,
      email: 'william.smith@example.com',
      city: 'Boston',
    },
    {
      id: 23,
      name: 'Emma Brown',
      age: 28,
      email: 'emma.brown@example.com',
      city: 'Denver',
    },
    {
      id: 24,
      name: 'Alexander Davis',
      age: 30,
      email: 'alexander.davis@example.com',
      city: 'San Francisco',
    },
    {
      id: 25,
      name: 'Mia Johnson',
      age: 32,
      email: 'mia.johnson@example.com',
      city: 'Austin',
    },
    {
      id: 26,
      name: 'James Brown',
      age: 29,
      email: 'james.brown@example.com',
      city: 'Dallas',
    },
  ];
  
  export default data;